# Lesson 06: numpy II

최규빈  
2023-07-24

<a href="https://colab.research.google.com/github/guebin/PP2024WIN/blob/main/posts/Day2/ls06.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" style="text-align: left"></a>

<https://youtu.be/playlist?list=PLQqh36zP38-y6ji16q-PFYlLKyEt2OwDp&si=a-t5jFK1QBV5GKUT>

# Imports

In [2]:
import numpy as np

# Numpy: axis의 이해

`-` 목표: 넘파이의 axis를 이해하여 보자.

## np.concatenate

`-` 기본예제

In [3]:
a=np.array([1,2]) 
b=-a

In [11]:
np.array(list(a) +list(b))

In [13]:
np.concatenate([a,b])

`-` 응용

In [14]:
a=np.array([1,2])
b=-a 
c=np.array([3,4,5])

In [58]:
np.concatenate([a,b,c])

-   여기까진 딱히 칸캐터네이트의 메리트가 없어보임
-   리스트였다면 a+b+c 하면 되는 기능이니까?

`-` 2d array에 적용해보자.

In [31]:
a=np.arange(4).reshape(2,2) 
b=-a

In [32]:
np.concatenate([a,b]) 

`-` 옆으로 붙일려면?

In [33]:
np.concatenate([a,b],axis=1)

`-` 위의 코드에서 axis=1 이 뭐지? axis=0,2 등을 치면 결과가 어떻게 될까?

In [39]:
np.concatenate([a,b],axis=0)

-   이건 그냥 np.concatenate(\[a,b\])와 같다.
-   np.concatenate(\[a,b\])는 np.concatenate(\[a,b\],axis=0)의
    생략버전이군?

In [65]:
np.concatenate([a,b],axis=2)

-   이런건 없다.

`-` axis의 의미가 뭔지 궁금함. 좀 더 예제를 살펴보자.

In [40]:
a=np.array(range(2*3*4)).reshape(2,3,4)
a

In [41]:
b=-a
b

In [70]:
np.concatenate([a,b],axis=0) 

In [72]:
np.concatenate([a,b],axis=1) 

In [73]:
np.concatenate([a,b],axis=2) 

-   이번에는 axis=2까지 된다?

In [75]:
np.concatenate([a,b],axis=3) 

-   axis=3까지는 안된다?

`-` 뭔가 나름의 방식으로 합쳐지는데 원리가 뭘까?

(분석1) np.concatenate(\[a,b\],axis=0)

In [80]:
a=np.array(range(2*3*4)).reshape(2,3,4) 
b=-a 

In [86]:
a.shape, b.shape, np.concatenate([a,b],axis=0).shape

-   첫번째차원이 바뀌었다 =\> 첫번째 축이 바뀌었다 =\> axis=0 (파이썬은
    0부터 시작하니까!)

(분석2) np.concatenate(\[a,b\],axis=1)

In [88]:
a=np.array(range(2*3*4)).reshape(2,3,4) 
b=-a 

In [89]:
a.shape, b.shape, np.concatenate([a,b],axis=1).shape

-   두번째차원이 바뀌었다 =\> 두번째 축이 바뀌었다 =\> axis=1

(분석3) np.concatenate(\[a,b\],axis=2)

In [90]:
a=np.array(range(2*3*4)).reshape(2,3,4) 
b=-a 

In [92]:
a.shape, b.shape, np.concatenate([a,b],axis=2).shape

-   세번째차원이 바뀌었다 =\> 세번째 축이 바뀌었다 =\> axis=2

(분석4) np.concatenate(\[a,b\],axis=3)

In [94]:
a=np.array(range(2*3*4)).reshape(2,3,4) 
b=-a 

In [95]:
a.shape, b.shape, np.concatenate([a,b],axis=3).shape

-   네번째차원이 없다 =\> 네번째 축이 없다 =\> axis=3으로 하면 에러가
    난다.

(보너스1)

In [99]:
a=np.array(range(2*3*4)).reshape(2,3,4) 
b=-a 

In [101]:
np.concatenate([a,b],axis=-1)

In [100]:
a.shape, b.shape, np.concatenate([a,b],axis=-1).shape

-   마지막 차원이 바뀌었다 =\> 마지막 축이 바뀌었다 =\> axis = -1

(보너스2)

In [107]:
a=np.array(range(2*3*4)).reshape(2,3,4) 
b=-a 

In [108]:
np.concatenate([a,b],axis=-2)

In [109]:
a.shape, b.shape, np.concatenate([a,b],axis=-2).shape

-   마지막에서 2번째 차원이 바뀌었다 =\> 마지막에서 2번째 축이 바뀌었다
    =\> axis = -2

(보너스3)

In [90]:
a=np.array(range(2*3*4)).reshape(2,3,4) 
b=-a 

In [111]:
np.concatenate([a,b],axis=-3)

In [112]:
a.shape, b.shape, np.concatenate([a,b],axis=-3).shape

-   마지막에서 3번째 차원이 바뀌었다 =\> 마지막에서 3번째 축이 바뀌었다
    =\> axis = -3

(보너스3)

In [114]:
a=np.array(range(2*3*4)).reshape(2,3,4) 
b=-a 

In [115]:
np.concatenate([a,b],axis=-4)

-   마지막에서 4번째 차원은 없다 =\> 마지막에서 4번째 축이 없다 =\> axis
    = -4는 에러가 난다.

`-` 0차원은 축이 없으므로 concatenate를 쓸 수 없다.

In [52]:
a= np.array(1)
b= np.array(-1) 

In [126]:
a.shape, b.shape

In [54]:
np.concatenate([a,b])

`-` 꼭 a,b가 같은 차원일 필요는 없다.

In [55]:
a=np.array(range(4)).reshape(2,2) 
b=np.array(range(2)).reshape(2,1)  

In [66]:
np.concatenate([a,b.T],axis=0)

In [131]:
np.concatenate([a,b],axis=1)

In [133]:
a.shape, b.shape, np.concatenate([a,b],axis=1).shape

## np.stack

`-` 혹시 아래가 가능할까?

-   (3,) 결합 (3,) =\> (3,2)

In [67]:
a=np.array([1,2,3])
b=-a

In [150]:
a,b

In [151]:
np.concatenate([a,b],axis=1)

-   불가능

`-` 아래와 같이 하면 해결가능

In [152]:
a=np.array([1,2,3]).reshape(3,1) 
b=-a

In [153]:
a,b

In [154]:
np.concatenate([a,b],axis=1)

-   분석: (3) (3) =\> (3,1) (3,1) =\> (3,1) concat (3,1)

`-` 위의 과정을 줄여서 아래와 같이 할 수 있다.

In [156]:
a=np.array([1,2,3])
b=-a

In [157]:
np.stack([a,b],axis=1)

`-` 아래도 가능

In [158]:
np.stack([a,b],axis=0)

`-` 분석해보고 외우자

(분석1)

In [159]:
a=np.array([1,2,3])
b=-a

In [162]:
a.shape, b.shape, np.stack([a,b],axis=0).shape

-   1.  1.  =\> 첫 위치에 축을 추가 (axis=0) =\> (1,3) (1,3) =\> (2,3)

(분석2)

In [163]:
a=np.array([1,2,3])
b=-a

In [164]:
a.shape, b.shape, np.stack([a,b],axis=1).shape

-   1.  1.  =\> 두 위치에 축을 추가 (axis=1) =\> (3,1) (3,1) =\> (3,2)

`-` 고차원예제

In [166]:
a=np.arange(3*4*5).reshape(3,4,5) 
b=-a

In [167]:
a.shape, b.shape

In [170]:
np.stack([a,b],axis=0).shape # (3,4,5) => (1,3,4,5) // 첫 위치에 축이 추가되고 스택 

In [174]:
np.stack([a,b],axis=1).shape # (3,4,5) => (3,1,4,5) // 두번째 위치에 축이 추가되고 스택 

In [175]:
np.stack([a,b],axis=2).shape # (3,4,5) => (3,4,1,5) // 세번째 위치에 축이 추가되고 스택 

In [179]:
np.stack([a,b],axis=3).shape # (3,4,5) => (3,4,5,1) // 네번째 위치에 축이 추가되고 스택 

In [181]:
np.stack([a,b],axis=-1).shape # axis=-1 <=> axis=3 

In [182]:
np.stack([a,b],axis=-2).shape # axis=-2 <=> axis=2

***np.concatenate*** 는 축의 총 갯수를 유지하면서 결합, ***np.stack***은
축의 갯수를 하나 증가시키면서 결합

## sum

`-` 1차원

In [121]:
a = np.array([1,2,3]) 
a

In [122]:
a.sum()

In [123]:
a.sum(axis=0)

`-` 2차원

In [208]:
a=np.array(range(6)).reshape(2,3)
a

In [209]:
a.sum() # 전체합

In [210]:
a.sum(axis=0) 

In [211]:
a.sum(axis=1) 

`-` 2차원 결과 분석

In [193]:
a.shape, a.sum(axis=0).shape

-   첫번째 축이 삭제됨 =\> axis=0

In [195]:
a.shape, a.sum(axis=1).shape

-   두번째 축이 삭제됨 =\> axis=1

`-` 연습

In [197]:
a=np.array(range(10)).reshape(5,2) 
a

(문제1) 1열의 합, 2열의 합을 계산하고 싶다면?

(풀이) 차원이 (5,2) =\> (2,) 로 나와야 한다. (그럼 첫번째 축이
삭제되어야 하네?)

In [198]:
a.sum(axis=0)

(문제2) 1행의 합, 2행의 합, … , 5행의 합을 계산하고 싶다면?

(풀이) 차원이 (5,2) =\> (5,)로 나와야 한다. (그럼 두번째 축이 삭제되어야
하네?)

In [199]:
a.sum(axis=1)

(문제3) a의 모든원소의 합을 계산하고 싶다면?

(풀이) 차원이 (5,2) =\> () 로 나와야 한다. (첫번째축, 두번째축이 모두
삭제되어야 하네?)

In [201]:
a.sum(axis=(0,1))

In [203]:
a.sum() # 즉 a.sum(axis=(0,1))이 디폴트값임 

## mean, max, min

`-` 모두 sum이랑 유사한 논리

In [136]:
a=np.array(range(10)).reshape(5,2)
a

In [7]:
a.mean(axis=0), a.max(axis=0), a.min(axis=0)

In [8]:
a.mean(axis=1), a.max(axis=1), a.min(axis=1)

# Quiz

`1` – `6`. a,b가 아래와 같이 주어졌다고 하자.

In [ ]:
a=np.array([1]*10)
b=np.array([2]*10)

`1`. a,b와 np.concatenate를 이용하여 아래와 같은 배열을 만들어라.

    array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

`2`. a,b와 np.concatenate를 이용하여 아래와 같은 배열을 만들어라.

In [ ]:
a=np.array([1]*10)
b=np.array([2]*10)

    array([[1],
           [1],
           [1],
           [1],
           [1],
           [1],
           [1],
           [1],
           [1],
           [1],
           [2],
           [2],
           [2],
           [2],
           [2],
           [2],
           [2],
           [2],
           [2],
           [2]])

`3`. a,b와 np.concatenate를 이용하여 아래와 같은 배열을 만들어라.

    array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
           [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]

`4`. a,b와 np.concatenate를 이용하여 아래와 같은 배열을 만들어라.

    array([[1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2]])

`5`. a,b와 np.stack을 이용하여 아래와 같은 배열을 만들어라.

    array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
           [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]

`6`. a,b와 np.stack을 이용하여 아래와 같은 배열을 만들어라.

    array([[1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2]])

**`7`–`8`**

아래와 같은 매트릭스를 생성하라.

In [ ]:
np.random.seed(43052)
a=np.random.randn(10000).reshape(100,100)
a

`7`. 각 행의 합을 구하라. 즉 1행의 합, 2행의 합, … 100행의 합을
계산하라.

-   1행의합 = 0.38342049 + 1.0841745 + … + 1.18701443

`8`. 각 열의 평균을 구하라. 즉 1열의 평균, 2열의 평균, … , 100열의
평균을 계산하라.